In [1]:
%pip install statsmodels

  Using cached statsmodels-0.14.6-cp314-cp314-win_amd64.whl.metadata (9.8 kB)
  Using cached patsy-1.0.2-py2.py3-none-any.whl.metadata (3.6 kB)
Using cached statsmodels-0.14.6-cp314-cp314-win_amd64.whl (9.6 MB)
Using cached patsy-1.0.2-py2.py3-none-any.whl (233 kB)

   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [st

In [11]:
import numpy as np
import torch
import gdown
import os

# ----------------------------------------------------------
# DOWNLOAD FROM GOOGLE DRIVE
# ----------------------------------------------------------

files = {
    "y_pred_dense": ("14YY9eZ8Fy_oVVcCgmI8o2kQ0dH_8e5cp", "multi_cancer_densenet121_preds.pth"),
    "y_pred_eff": ("141qY1T0Nz9NSME-CV2G_cjW7j-Fa3oZG", "multi_cancer_effcientnet_preds.pth"),
    "y_pred_mobile": ("1OIMDeEMY_Sw-xu-9bXVM79VwljdO2-cG", "multi_cancer_mobilenetv3_preds.pth"),
    "y_pred_resnet": ("1EfaCow3dsVexaJvx0_0xikEQzVD6VsTQ", "multi_cancer_resnet18_preds.pth"),
    "y_true": ("17vQCBituqWYZGZiiJL_P8R9H8uYedkWA", "y_true.pth")
}

os.makedirs("downloads", exist_ok=True)

for name, (file_id, filename) in files.items():
    path = f"downloads/{filename}"
    
    if not os.path.exists(path):
        url = f"https://drive.google.com/uc?id={file_id}"
        print(f"Downloading {filename}...")
        gdown.download(url, path, quiet=False)
    else:
        print(f"{filename} already exists, skipping download.")

# ----------------------------------------------------------
# LOAD FILES (PyTorch 2.6 FIX INCLUDED)
# ----------------------------------------------------------

import torch.serialization
torch.serialization.add_safe_globals([np.core.multiarray._reconstruct])

y_true = torch.load("downloads/y_true.pth", weights_only=False)

y_pred_dense = torch.load("downloads/multi_cancer_densenet121_preds.pth", weights_only=False)
y_pred_eff   = torch.load("downloads/multi_cancer_effcientnet_preds.pth", weights_only=False)
y_pred_mobile= torch.load("downloads/multi_cancer_mobilenetv3_preds.pth", weights_only=False)
y_pred_resnet= torch.load("downloads/multi_cancer_resnet18_preds.pth", weights_only=False)

# Convert to numpy
y_true = np.array(y_true)
y_pred_dense = np.array(y_pred_dense)
y_pred_eff = np.array(y_pred_eff)
y_pred_mobile = np.array(y_pred_mobile)
y_pred_resnet = np.array(y_pred_resnet)

print("\n✅ All files loaded successfully!")
print("Shape check:")
print("y_true:", y_true.shape)
print("Dense:", y_pred_dense.shape)
print("Eff:", y_pred_eff.shape)
print("Mobile:", y_pred_mobile.shape)
print("ResNet:", y_pred_resnet.shape)

Downloading...
From: https://drive.google.com/uc?id=14YY9eZ8Fy_oVVcCgmI8o2kQ0dH_8e5cp
To: c:\Files\IISc\AI in Health Care\Multi Cancer\Multi Cancer\downloads\multi_cancer_densenet121_preds.pth
100%|██████████| 19.6k/19.6k [00:00<00:00, 18.5MB/s]


Downloading...
From: https://drive.google.com/uc?id=141qY1T0Nz9NSME-CV2G_cjW7j-Fa3oZG
To: c:\Files\IISc\AI in Health Care\Multi Cancer\Multi Cancer\downloads\multi_cancer_effcientnet_preds.pth
100%|██████████| 19.6k/19.6k [00:00<00:00, 4.10MB/s]


Downloading...
From: https://drive.google.com/uc?id=1OIMDeEMY_Sw-xu-9bXVM79VwljdO2-cG
To: c:\Files\IISc\AI in Health Care\Multi Cancer\Multi Cancer\downloads\multi_cancer_mobilenetv3_preds.pth
100%|██████████| 19.6k/19.6k [00:00<00:00, 2.84MB/s]


Downloading...
From: https://drive.google.com/uc?id=1EfaCow3dsVexaJvx0_0xikEQzVD6VsTQ
To: c:\Files\IISc\AI in Health Care\Multi Cancer\Multi Cancer\downloads\multi_cancer_resnet18_preds.pth
100%|██████████| 19.6k/19.6k [00:00<00:00, 3.07MB/s]


Downloading...
From: https://drive.google.com/uc?id=17vQCBituqWYZGZiiJL_P8R9H8uYedkWA
To: c:\Files\IISc\AI in Health Care\Multi Cancer\Multi Cancer\downloads\y_true.pth
100%|██████████| 19.4k/19.4k [00:00<00:00, 906kB/s]


✅ All files loaded successfully!
Shape check:
y_true: (2250,)
Dense: (2250,)
Eff: (2250,)
Mobile: (2250,)
ResNet: (2250,)



C:\Users\RoupB\AppData\Local\Temp\ipykernel_872\3074243075.py:35: DeprecationWarning: numpy.core is deprecated and has been renamed to numpy._core. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.multiarray.
  torch.serialization.add_safe_globals([np.core.multiarray._reconstruct])


In [12]:
import numpy as np
import torch
from statsmodels.stats.contingency_tables import mcnemar, cochrans_q

In [13]:
# HANDLE PROBABILITIES

def to_labels(pred):
    # If predictions are probabilities/logits
    if len(pred.shape) > 1:
        return np.argmax(pred, axis=1)
    return pred

y_pred_dense = to_labels(y_pred_dense)
y_pred_eff = to_labels(y_pred_eff)
y_pred_mobile = to_labels(y_pred_mobile)
y_pred_resnet = to_labels(y_pred_resnet)

In [14]:
# SAFETY CHECK

assert len(y_true) == len(y_pred_dense) == len(y_pred_eff) == len(y_pred_mobile) == len(y_pred_resnet), "Mismatch in lengths!"


In [15]:
# CONVERT TO CORRECT / INCORRECT

dense_correct = (y_pred_dense == y_true).astype(int)
eff_correct = (y_pred_eff == y_true).astype(int)
mobile_correct = (y_pred_mobile == y_true).astype(int)
resnet_correct = (y_pred_resnet == y_true).astype(int)

In [16]:
# COCHRAN’S Q TEST

from statsmodels.stats.contingency_tables import cochrans_q

data = np.vstack([
    dense_correct,
    eff_correct,
    mobile_correct,
    resnet_correct
]).T

# Run test
result = cochrans_q(data)

# Extract values correctly
q_stat = result.statistic
p_value = result.pvalue

print("\n🔹 Cochran’s Q Test")
print("Q-statistic:", q_stat)
print("p-value:", p_value)


🔹 Cochran’s Q Test
Q-statistic: 2574.211758301579
p-value: 0.0


In [17]:
# MCNEMAR TEST

def run_mcnemar(model1, model2, name1, name2):
    table = np.zeros((2, 2))

    for i in range(len(y_true)):
        table[model1[i], model2[i]] += 1

    result = mcnemar(table, exact=True)

    print(f"\n🔸 {name1} vs {name2}")
    print("Table:\n", table)
    print("p-value:", result.pvalue)

In [18]:
# Pairwise tests
run_mcnemar(dense_correct, eff_correct, "DenseNet", "EfficientNet")
run_mcnemar(dense_correct, mobile_correct, "DenseNet", "MobileNet")
run_mcnemar(dense_correct, resnet_correct, "DenseNet", "ResNet")
run_mcnemar(eff_correct, mobile_correct, "EfficientNet", "MobileNet")
run_mcnemar(eff_correct, resnet_correct, "EfficientNet", "ResNet")
run_mcnemar(mobile_correct, resnet_correct, "MobileNet", "ResNet")



🔸 DenseNet vs EfficientNet
Table:
 [[ 150. 1371.]
 [  96.  633.]]
p-value: 2.099822809424746e-289

🔸 DenseNet vs MobileNet
Table:
 [[ 164. 1357.]
 [ 125.  604.]]
p-value: 9.124405753723547e-262

🔸 DenseNet vs ResNet
Table:
 [[ 139. 1382.]
 [ 124.  605.]]
p-value: 3.991929983108391e-269

🔸 EfficientNet vs MobileNet
Table:
 [[  90.  156.]
 [ 199. 1805.]]
p-value: 0.025666910882391095

🔸 EfficientNet vs ResNet
Table:
 [[  92.  154.]
 [ 171. 1833.]]
p-value: 0.3748253580707024

🔸 MobileNet vs ResNet
Table:
 [[  88.  201.]
 [ 175. 1786.]]
p-value: 0.19723642137584366


Based on the sigfiniace level Desnset performs the best out of all four models.
